### ISSUE TITLE
using metolib in serverside/nodejs

### ISSUE THREAD

**Issue by hiitsu** [fmidev/metolib#2]
Hi guys, i was just wondering if its possible to run this library in server side using nodejs? i ran quick experiment wrapping metolib-combined into node module and giving refs to jquery port, lodash and async, and i got xml parse problem. The unofficial node jQuery port is known to have problems with XML parsing and such, but if this problem is excluded do you see any reason why this couldn't be used serverside now or in the future?

**Comment by TopiasYM** [comment]
Still no possibility to use on nodejs?

I'm a beginner and hiitsu's way sounds too complicated.
